export const NAVIGATION = {
  HOME: {
    STACK: 'NAVIGATION.HOME.STACK',
    HOME: 'NAVIGATION.HOME.HOME',
    DETAILS: 'NAVIGATION.HOME.DETAILS',
  },
  FAV: {
    FAV: 'NAVIGATION.FAV.FAV',
  },
};
