const SCREEN_NAMES = {
  TAB_NAVIGATION: 'TAB_NAVIGATION',
  HOME: 'HOME',
  PHOTO: 'PHOTO',
  DETAIL_PHOTO_STACK: 'DETAIL_EVENT_STACK',
  DETAIL_PHOTO: 'DETAIL_PHOTO',
} as const

export { SCREEN_NAMES }
